package entity;
// Generated 29.08.2016 16:09:18 by Hibernate Tools 4.3.1

import java.sql.Date;




/**
 * CommentFilm generated by hbm2java
 */
public class CommentFilm  implements java.io.Serializable {


     private long id;
     private String comment;
     private Film film;
     private String username;
     private Date date;
     private User user;
     private boolean mycom;

    public void setMycom(boolean mycom) {
        this.mycom = mycom;
    }

    public boolean isMycom() {
        return mycom;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public User getUser() {
        return user;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public void setFilm(Film film) {
        this.film = film;
    }

    
    public void setUsername(String username) {
        this.username = username;
    }

    
    public long getId() {
        return id;
    }

    public String getComment() {
        return comment;
    }

    public Film getFilm() {
        return film;
    }

    public String getUsername() {
        return username;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    

    public CommentFilm() {
    }


}


