package entity;
// Generated 29.08.2016 16:09:18 by Hibernate Tools 4.3.1


import java.util.Set;




/**
 * Genre generated by hbm2java
 */
public class Genre  implements java.io.Serializable {


     private long id;
     private String title;
     private Set<Film> films;

    public void setId(long id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setFilms(Set<Film> films) {
        this.films = films;
    }

    public long getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public Set<Film> getFilms() {
        return films;
    }

    public Genre() {
    }

	
    public Genre(long id) {
        this.id = id;
    }
    


}


